[[member]]
name = "Ulrich Dirnagl"
institution = "BIH QUEST-Center @ Charité Berlin"
image = "members/images/dirnagl.jpg"
url = "https://expneuro.charite.de/en/metas/person_detail/person/address_detail/dirnagl-1/"
twitter = "dirnagl"

[[member]]
name = "Christian Fiebach"
institution = "Goethe University Frankfurt"
image = "members/images/fiebach.jpg"
url = "http://www.fiebachlab.org/"
twitter = "FiebachLab"

[[member]]
name = "Susann Fiedler"
institution = "Max Planck Institute for Research on Collective Goods, Bonn"
image = "members/images/fiedler.jpg"
url = "https://sites.google.com/site/susannfiedler/"
twitter = "susafiedler"

[[member]]
name = "Bernadette Fritzsch"
institution = "Alfred-Wegner-Institute"
image = "members/images/fritzsch.jpg"
url = "https://www.awi.de/en/about-us/organisation/staff/bernadette-fritzsch.html"

[[member]]
name = "Felix Henninger"
institution = "University of Mannheim"
image = "members/images/henninger.jpg"
url = "https://www.felixhenninger.com/"
twitter = "felixhenninger"

[[member]]
name = "Nikolaus Plesnila"
institution = "Ludwig-Maximilians-University Munich"
image = "members/images/plesnila.jpg"
url = "https://www.lmu-klinikum.de/isd"

[[member]]
name = "Rima-Maria Rahal"
institution = "Max Planck Institute for Research on Collective Goods, Bonn"
image = "members/images/rahal.jpg"
url = "https://rimamrahal.wordpress.com/"
twitter = "rimamrahal"

[[member]]
name = "Guido Scherp"
institution = "Leibniz Information Centre for Economics"
image = "members/images/scherp.jpg"
url = "https://www.zbw.eu/en/research/science-2-0/guido-scherp"
twitter = "guido_scherp"

[[member]]
name = "Felix Schönbrodt"
institution = "Ludwig-Maximilians-University Munich"
image = "members/images/schoenbrodt.jpg"
url = "https://www.nicebread.de/"
twitter = "nicebread"

[[member]]
name = "Antonia Schrader"
institution = "Helmholtz Association Open Science Office"
image = "members/images/schrader.jpg"
url = "https://os.helmholtz.de/"
twitter = "helmholtz_os"

[[member]]
name = "Heidi Seibold"
institution = "Helmholtz AI"
image = "members/images/seibold.jpg"
url = "https://www.helmholtz.ai/themenmenue/our-research/research-groups/seibolds-group/index.html"
twitter = "heidibaya"

[[member]]
name = "Klaus Tochtermann"
institution = "Leibniz Information Centre for Economics"
image = "members/images/tochtermann.jpg"
url = "https://www.zbw.eu/en/research/klaus-tochtermann/"
twitter = "ktochtermann"

[[member]]
name = "Ulf Toelch"
institution = "BIH QUEST-Center @ Charité Berlin"
image = "members/images/toelch.jpg"
twitter = "ulf_toelch"

[[member]]
name = "Stefanie Weigold"
institution = "BIH QUEST-Center @ Charité Berlin"
image = "members/images/weigold.jpg"
